FROM python:3.12-slim
WORKDIR /app

RUN pip install uv

COPY requirements.in .

# compile and install in one step, correct arch guaranteed
RUN uv pip compile requirements.in -o requirements.txt && \
    uv pip sync requirements.txt

RUN python3 -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
