"""
One-time COPR → ChromaDB ingestion script.

Run inside the backend container after the stack is up:
    podman exec -it drillbit_backend_1 python ingest.py

Progress is printed to stdout. Safe to re-run — upsert is idempotent.

Flags: --dry-run (preview only, no writes) and --since DATE (filter by each
package's latest COPR build submission time — see package_updated_since()).
"""

import argparse
import hashlib
import sys
import time
from collections import Counter
from datetime import UTC, datetime

import httpx
from chroma import collection
from scorer import compute_scores
from sentence_transformers import SentenceTransformer

COPR_API = "https://copr.fedorainfracloud.org/api_3"
BATCH_SIZE = 64  # embeddings batch size
PROJECT_PAGE_SIZE = 100  # max allowed by COPR API
PKG_PAGE_SIZE = 100
MAX_PROJECTS = None  # set to an integer to cap project traversal (useful for testing)
MAX_PACKAGES = 1000  # only the top-scored packages are indexed

# Templated strings generated by COPR and Packit — reliable enough for exact substring matching.
NOISE_DESCRIPTION_MARKERS = (
    "Continuous builds initiated by Packit service",
    "Very likely personal repository for testing purpose",
)
NOISE_INSTRUCTIONS_MARKERS = (
    "This copr project is created and handled by the Packit project",
    "Everybody else should avoid this repo",
)

model = SentenceTransformer("all-MiniLM-L6-v2")


def score_range(scored: list[tuple[float, dict]]) -> tuple[float, float]:
    """Return (min, max) score among the packages that will actually be indexed
    (i.e. the top MAX_PACKAGES of scored, which is sorted descending)."""
    score_min = scored[min(len(scored), MAX_PACKAGES) - 1][0]
    score_max = scored[0][0]
    return score_min, score_max


def package_hash(package: dict) -> str:
    """Generate a SHA256 hash for a package based on its name, summary, and description."""
    raw = f"{package.get('name', '')}:{package.get('summary', '')}:{package.get('description', '')}"
    return hashlib.sha256(raw.encode()).hexdigest()


def copr_get(client: httpx.Client, path: str, params: dict) -> dict:
    """GET from COPR API with basic retry on transient errors."""
    url = f"{COPR_API}{path}"
    for attempt in range(5):
        try:
            r = client.get(url, params=params, timeout=30)
            r.raise_for_status()
            return r.json()
        except (httpx.HTTPStatusError, httpx.TransportError) as e:
            if attempt == 4:
                raise
            wait = 2**attempt
            print(f"  retrying {url} in {wait}s ({e})")
            time.sleep(wait)


def is_noise_project(description: str, instructions: str) -> bool:
    return any(m in description for m in NOISE_DESCRIPTION_MARKERS) or any(
        m in instructions for m in NOISE_INSTRUCTIONS_MARKERS
    )


def fetch_project_details(
    client: httpx.Client, ownername: str, projectname: str
) -> tuple[str, bool]:
    """Fetch instructions and unlisted status for a COPR project.

    Returns (instructions, unlisted_on_hp). Both values default to safe values
    on any error so the project is not incorrectly dropped.
    """
    try:
        data = copr_get(
            client, "/project", {"ownername": ownername, "projectname": projectname}
        )
        instructions = (data.get("instructions") or "").strip()
        unlisted_on_hp = data.get("unlisted_on_hp", True)
        return instructions, unlisted_on_hp
    except Exception:
        return "", True


def iter_projects(client: httpx.Client):
    """Yield all COPR projects, paginating through the full list."""
    offset = 0
    while True:
        data = copr_get(
            client,
            "/project/list",
            {
                "limit": PROJECT_PAGE_SIZE,
                "offset": offset,
            },
        )
        projects = data.get("items") or data.get("projects") or []
        if not projects:
            break
        yield from projects
        if len(projects) < PROJECT_PAGE_SIZE:
            break
        offset += PROJECT_PAGE_SIZE


def iter_packages(
    client: httpx.Client, ownername: str, projectname: str, with_latest_build: bool = False
):
    """Yield all packages in a COPR project.

    with_latest_build=True asks COPR to embed each package's latest build
    (including its submitted_on timestamp) in the response — see
    package_updated_since(). It's opt-in because it adds payload weight we
    don't need on a normal, non-filtered crawl.
    """
    offset = 0
    while True:
        params = {
            "ownername": ownername,
            "projectname": projectname,
            "limit": PKG_PAGE_SIZE,
            "offset": offset,
        }
        if with_latest_build:
            params["with_latest_build"] = True
        data = copr_get(client, "/package/list", params)
        packages = data.get("items") or data.get("packages") or []
        if not packages:
            break
        yield from packages
        if len(packages) < PKG_PAGE_SIZE:
            break
        offset += PKG_PAGE_SIZE


def parse_since(value: str) -> float:
    """Parse a YYYY-MM-DD date string into a UTC unix timestamp."""
    try:
        dt = datetime.strptime(value, "%Y-%m-%d")
    except ValueError as e:
        raise argparse.ArgumentTypeError(f"invalid date '{value}', expected YYYY-MM-DD") from e
    return dt.replace(tzinfo=UTC).timestamp()


def package_updated_since(package: dict, since_ts: float) -> bool:
    """Return True if package's latest COPR build was submitted on/after since_ts.

    COPR's API exposes no last-modified timestamp on projects or packages
    themselves (confirmed against the live /project/list, /project, and
    /package/list responses — none carry one). The latest build's
    submitted_on (available per-package via /package/list?with_latest_build=True)
    is the closest genuine per-package activity signal COPR offers, so --since
    filters on it. Packages with no recorded build have no timestamp to
    compare and are treated as not updated.
    """
    latest = (package.get("builds") or {}).get("latest")
    if not latest:
        return False
    submitted_on = latest.get("submitted_on")
    return submitted_on is not None and submitted_on >= since_ts


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Crawl COPR and index package metadata into ChromaDB.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run the full crawl/scoring pipeline but skip writing to ChromaDB; print a preview instead.",
    )
    parser.add_argument(
        "--since",
        type=parse_since,
        default=None,
        metavar="YYYY-MM-DD",
        help=(
            "Only index packages whose latest COPR build was submitted on or after this date. "
            "COPR has no project/package 'last modified' field, so this filters on the latest "
            "build's submission time instead — see package_updated_since()."
        ),
    )
    return parser.parse_args(argv)


def flush_batch(ids, texts, metadatas, hashes):
    """Upsert a batch of documents, skipping unchanged ones based on content hash."""
    existing = collection.get(ids=ids, include=["metadatas"])
    existing_hashes = {
        doc_id: meta.get("content_hash")
        for doc_id, meta in zip(existing["ids"], existing["metadatas"])
    }

    new_ids, new_texts, new_metas = [], [], []
    for uid, text, meta, h in zip(ids, texts, metadatas, hashes):
        if existing_hashes.get(uid) != h:
            meta["content_hash"] = h
            new_ids.append(uid)
            new_texts.append(text)
            new_metas.append(meta)

    if not new_ids:
        return  # entire batch unchanged, skip embedding call

    embeddings = model.encode(new_texts).tolist()
    collection.upsert(
        ids=new_ids, embeddings=embeddings, documents=new_texts, metadatas=new_metas
    )


def main(dry_run: bool = False, since_ts: float | None = None):
    all_packages = []  # list of (uid, text, metadata, hash)
    cross_project_counts = Counter()  # package_name → # of projects containing it
    total_projects = 0
    packages_skipped_stale = 0

    with httpx.Client() as client:
        for project in iter_projects(client):
            if MAX_PROJECTS and total_projects >= MAX_PROJECTS:
                break

            owner = project.get("ownername") or project.get("owner", {}).get("name", "")
            name = project.get("name") or project.get("projectname", "")
            description = project.get("description") or ""
            if not owner or not name or not description.strip():
                continue  # skip empty/undescribed projects

            # Phase 1: cheap description check — no extra API call
            if any(m in description for m in NOISE_DESCRIPTION_MARKERS):
                continue

            # Phase 2: instructions check — extra /project call, only for projects that
            # passed the description filter. Also captures unlisted_on_hp for scoring.
            instructions, unlisted_on_hp = fetch_project_details(client, owner, name)
            if any(m in instructions for m in NOISE_INSTRUCTIONS_MARKERS):
                continue

            total_projects += 1
            if total_projects % 100 == 0:
                print(
                    f"projects={total_projects}  packages={len(all_packages)}",
                    flush=True,
                )

            pkg_iter = (
                iter_packages(client, owner, name, with_latest_build=True)
                if since_ts is not None
                else iter_packages(client, owner, name)
            )
            try:
                for pkg in pkg_iter:
                    if since_ts is not None and not package_updated_since(pkg, since_ts):
                        packages_skipped_stale += 1
                        continue

                    pkg_name = pkg.get("name", "")
                    summary = pkg.get("summary") or ""
                    pkg_description = pkg.get("description") or ""

                    text = f"{pkg_name}: {summary}" if summary else pkg_name
                    uid = f"{owner}/{name}/{pkg_name}"

                    cross_project_counts[pkg_name] += 1

                    all_packages.append(
                        (
                            uid,
                            text,
                            {
                                "name": pkg_name,
                                "summary": summary[:500],
                                "description": pkg_description[:1000],
                                "copr_project": f"{owner}/{name}",
                                "ownername": owner,
                                "projectname": name,
                                "unlisted_on_hp": unlisted_on_hp,
                            },
                            package_hash(pkg),
                        )
                    )

            except Exception as e:
                print(f"  skipping {owner}/{name}: {e}", file=sys.stderr)
                continue

    # Score all collected packages and cap at MAX_PACKAGES
    total_collected = len(all_packages)
    print(
        f"\nScoring {total_collected} packages from {total_projects} projects...",
        flush=True,
    )
    if since_ts is not None:
        print(f"  ({packages_skipped_stale} packages skipped: no build on/after --since)")

    pkg_metas = [meta for _, _, meta, _ in all_packages]
    scored = compute_scores(pkg_metas, cross_project_counts)

    top_uids = {
        f"{meta['ownername']}/{meta['projectname']}/{meta['name']}": score
        for score, meta in scored[:MAX_PACKAGES]
    }

    if dry_run:
        if scored:
            score_min, score_max = score_range(scored)
            print(
                f"[dry-run] Would index top {len(top_uids)} of {total_collected} scored "
                f"packages from {total_projects} projects. Score range: "
                f"{score_min:.2f}-{score_max:.2f}. No writes were made to ChromaDB."
            )
        else:
            print("[dry-run] No packages found to index. No writes were made to ChromaDB.")
        return

    # Upsert top-N in batches, adding popularity_score to stored metadata
    ids, texts, metadatas, hashes = [], [], [], []
    total_pkgs = 0

    for uid, text, meta, h in all_packages:
        if uid not in top_uids:
            continue
        meta = {**meta, "popularity_score": round(top_uids[uid], 4)}
        ids.append(uid)
        texts.append(text)
        metadatas.append(meta)
        hashes.append(h)

        if len(ids) >= BATCH_SIZE:
            flush_batch(ids, texts, metadatas, hashes)
            total_pkgs += len(ids)
            ids, texts, metadatas, hashes = [], [], [], []

    if ids:
        flush_batch(ids, texts, metadatas, hashes)
        total_pkgs += len(ids)

    if scored:
        score_min, score_max = score_range(scored)
        print(
            f"Done. Scored {total_collected} packages, indexed top {total_pkgs}. "
            f"Score range: {score_min:.2f}-{score_max:.2f}"
        )
    else:
        print("Done. No packages found to index.")


if __name__ == "__main__":
    cli_args = parse_args()
    main(dry_run=cli_args.dry_run, since_ts=cli_args.since)
