FROM python:3.12-slim

WORKDIR /app

COPY requirements.in .

RUN pip install pip-tools && \
    pip-compile requirements.in && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["python", "main.py"]
