FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY requirements.in .

# compile and install in one step, correct arch guaranteed
RUN uv pip compile requirements.in -o requirements.txt && \
    uv pip sync requirements.txt

COPY . .

EXPOSE 8001

CMD ["python", "main.py"]
